### ISSUE TITLE
Replace Tarallo.status() with something more efficient

### ISSUE THREAD

**Issue by ghost** [WEEE-Open/pytarallo#14]
As pointed out here https://github.com/WEEE-Open/python-tarallo/issues/6#issuecomment-436801357,
the login() method already checks its own request status by returning a boolean.

We should at the end of each request:
1. Check the `status_code` for `403`
2. If it's `403`, attempt `login()`
3. If `login()` returns `True` try to resend the request, else QUIT
4. If the `status_code` is still `403` after resending the request after successful login, QUIT

The easiest way would be repeating the same piece of code for each method,
but sounds trivial, however making a method for this procedure requires
additional attention.

**Comment by Hyd3L** [comment]
#6

**Comment by lvps** [comment]
What about a custom decorator that retries the function call (just once) on a 403 response, if that's actually possible?
