### ISSUE TITLE
Create custom errors/exceptions

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/pytarallo#18]
NotFoundError, NotAuthorizedError, ValidationError, any other? Please suggest.

**Comment by ghost** [comment]
ValidationError I suppose is a sort of APIv1 related stuff.
What happens if the APIv1 can't evaluate a request? What does it return?

**Comment by lvps** [comment]
For ValidationError I was thinking stuff like "this code contains invalid characters" or "you can't place that item there".

If the API can't evaluate a request to the point that it doesn't even understand what you meant it returns a 400 Bad Request response, or sometimes a 500 but that's a bug and you should report these cases as they happen

**Comment by ghost** [comment]
The API still lacks of the `ValidationError`...
