### ISSUE TITLE
Create a custom ItemNotFoundError exception class

### ISSUE THREAD

**Issue by ghost** [WEEE-Open/pytarallo#19]
Must be raised here:

https://github.com/WEEE-Open/python-tarallo/blob/aac1f5b70ca896e613a6b20632a53cd2ec40dd8f/tarallo.py#L45

#18

**Comment by lvps** [comment]
In a "move" operation both the item and its parent could be non existing. The server returns the same code (404 IIRC) but with a different message and possibly a different machine-readable code in the response.

What do we do on the client? Do we use this exception for both or create 1 more or 2 more exceptions?

**Comment by ghost** [comment]
Then let's create another `LocationNotFoundError` exception

**Comment by lvps** [comment]
Sounds good, we can use it for new items when their location doesn't exist, too

**Comment by Hyd3L** [comment]
#27
