### ISSUE TITLE
Remove the JSON configuration file

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/pytarallo#5]
Have you ever seen a library that needs configuration? No? Me neither, just pass those 3 parameters to class constructors and do things the normal way! asd

**Comment by ghost** [comment]
What about leaving both possibilities? asd

**Comment by ghost** [comment]
It's more comfortable to edit a prefab JSON rather than adding environment variables to the virtualenvs.

**Comment by lvps** [comment]
Why do you need to add those variables to the library itself? Why can't they be supplied by whatever program uses the library? Why can't you use it like a library, i.e. have an example program (if you want to test the library without writing automated tests) with its own JSON file or whatever but the library doesn't read that file and just receives these strings as method parameters?

Finally, do you plan to add plaintext username and password to the bot repository since this library can only load them from JSON files?

**Comment by ghost** [comment]
OKANE asd
