### ISSUE TITLE
Implement caching/retrying in login function

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/pytarallo#6]
Well, #3 has to be done first, obviously.

Each time you log in, you receive a session cookie to be used for later requests. The cookie expires after a few hours that's not being used (currently 6 hours) or may be revoked at any time. Since you can't see the clock on the server, don't count time on the client, but correctly handle random 403 responses when session has expired. There are 3 ways to do it:

* POST to /v1/session before each request: terribly slow and inefficient since it needs to hash the password each time, don't do it, please don't, just don't
* GET /v1/session before each request, if it returns 200 then the session is still valid, if it returns 403 it has expired or there's some other problem, so try to log in once more. The bot currently does this, but it always sends two requests...
* The most complex but best way: send your request, if it returns 403 then POST to /v1/session and send request again. This has to be done for each and every request.

**Comment by ghost** [comment]
The third point is not such complex, we have the `Tarallo.request` attribute that saves the last request,
it's just a matter of creating a method that returns `False` if `Tarallo.request.status_code == 403`.

**Comment by ghost** [comment]
This is a nice problem of optimization, on one hand we have a working `Tarallo.status()` method that does the GET request to `/v1/session`...
On the other hand... we're potentially doing two requests.

Let's count the number of needed HTTP requests...

**In the first case** we avoid problems with a check before doing, so we make a request to avoid making another useless request and attempt to login just one single time.

So we have in the best case:
1. Check
2. True -> Do the actual request
END

In the worst case:
1. Check
2. False -> Login
3. Check
4. If True -> Do the actual request else QUIT
END

**In the second case**, we send the request that eventually gets a `403` as response, and parse the response at the end of each request, that actually doesn't sound so bad, it's similar to a Stop n' Wait network protocol.

Best case:
1. Send the request and check the Tarallo.request.status_code
END

Worst case:
1. Send the request and check the Tarallo.request.status_code
2. status_code is 403 -> login
3. Send the request again and check the Tarallo.request.status_code, if it's 403 again QUIT
END

Yea! We would save 1 HTTP request each time. Sounds nice

**Comment by Hyd3L** [comment]
#14

**Comment by ghost** [comment]
#23
