### ISSUE TITLE
Copy code from the bot

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/pytarallo#7]
Copy it here, reimplement same functionality, replace bot implementation with this library.

**Comment by ghost** [comment]
What about stopping opening GIANT and depressing issues and beginning with opening a lot of SMALL issues that someone would likely actually close? asd

**Comment by lvps** [comment]
The issue is **copying and pasting code**, the rest can be done later asd

**Comment by ghost** [comment]
There's still some code to copy asd

**Comment by lvps** [comment]
Provide more details: which methods? Where do we place them?

@Hyd3L you're the mind behind this project, the master planner of masterplans, create some methods to be implemented so people can copy and paste code asd
